---
title: "Long Life Learning: Preparing for Jobs that Don't Even Exist Yet (book review) "
author: "Zahid Asghar"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LONG LIFE LEARNING 

In her book [Long Life Learning: Preparing for Jobs that Don't Even Exist Yet](https://www.wiley.com/en-sg/Long+Life+Learning:+Preparing+for+Jobs+that+Don't+Even+Exist+Yet-p-9781119597483) ,Michelle R. Weise highlights that due to fast chaning world and due to rapid emergence and penetration of digital technologies, artificial intelligence, Machine Learning among many others, there is need to develop a new learning ecosystem. This book is although written mainly for a country like United States but these points are equally important for low income countries like Pakistan. 

Even if our graduates are well trained and have requisite skills for job market, its the case that skilling gap emerge overtime due to technological advances. People become less productive and there are not many opportunities for upskilling besides affordability issue. 

Life expectancy has been increasing by 2 to 3 years with every 10 years over the past two centuries and it is expected that life expectancy of people born in next 30 years may reach to more than 120 years. Due to increase in life expectancy over time across the globe, there is a need for paradigm shift from earning degree with some level of learning and then spending one’s rest of the life in job market with those skills. One has to switch a number of jobs and each job has its particular skill requirements. Many workers will never regain their pre-covid jobs as those jobs will never be back in the market as post-covid jobs skills may be more challenging or different in nature.  

This requires re imagining __LEARN, EARN AND REST to LEARN and EARN, LEARN and EARN, and LEARN and EARN...__
This continuously changing nature of jobs skills demand that one has to become a lifelong learner or the one who continuously upgrade one’s skills. Now question is: are there such opportunities of continuously improving one’s skills or learning new skills? Many jobs still prefer degree over what one knows. Are we ready for part time learning opportunities in our universities and colleges so one can complete one’s degree in a part time program and stay in labor force. Are there programs available where one can learn new skills while staying on job? Will our universities serve those who are unserved? 

Moreover, who will cater the needs of burgeoning youth which did'nt get opportunities by the universities either due to very high cost of education or due to somehow getting lower score in some class(es)
These are fundamental questions one need to address at national, provincial, regional and university level. 

How our education system is taking up this pace of technology change?
Are we preparing children for jobs of the future and kinds of industry and economy within that when they leave college/university?
Jeremy Howard (data scientist and AI) says not at all. He says its sad that basic computer skills and basic data analysis tools are not taught the way it should be even in the US.
Weise asks for developing a comprehensive _Learning Ecosystem_ and to shift goal post from *TIME* as fixed and *LEARNING* as *variable* to keep *LEARNING* fixed and *TIME* as *variable*. When *LEARNING* will be fixed then it will not matter whether its online platform or Physicial (full time/part time) as one cant go to next step unless one has those pre-requisite skills. She also emphasizes that university learning ecosystem should enable graduates to start moving on a continuous learning path rather simply focusing on imparting certain skills.
Its a very timely book providing enough food for thought for all of us to rethink about our higher educatin system to meet challenges of new technologies.



This study is aimed at how digital revolution is creating opportunities and how our universities can tap those opportunities to put our burgeoning youth on a learning path so they can become lifelong learners. Universities are at the most trying to build themselves to attain status as opposed to broad set of institutional outcomes having utility for the society. To get their improved ranking, they are rejecting more students than accepting. How universities can transform to have inclusive learning and using technological changes can provide education to all at a very low cost. This changing role of universities will create a demographic dividend for Pakistan which may play an active role for economic prosperity. Changing university education by having full time in person to digital emersion for online students, part time learning for workers and courses for people of every age will help to have opportunities to excel now and in future. This study contributes to reimagining university education to tap opportunities created by covid-19 disruption and enabling graduates to learn the process of getting skills. Future jobs skills are hardly know to anyone. Traditional university education system is misaligned with current job market and simply adding technological learning management system on it will not resolve the issue. The future of both higher education and jobs nature is uncertain, and many potential futures exists. Similarly, future skill requirements are also This study will launch a new debate about rethinking university role to tap opportunities to excel now and in future.
